language: ruby
cache: bundler

rvm:
 - "2.4.0"

env:
 - TRAVIS_NODE_VERSION="6"

services:
  - postgresql

before_install:
 - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

install:
  - bundle install
  - npm --prefix client install

script:
  - bundle exec rspec spec
  - npm --prefix client run lint
