language: ruby
cache: bundler

rvm:
 - "2.4.0"

env:
  - TRAVIS_NODE_VERSION="6"

services:
  - postgresql

install:
  - bundle install
  - npm --prefix client install

before_script:
  - psql -c 'create database tabbit_rabbit_api_test;' -U postgres

script:
  - bundle exec rspec spec
  - npm --prefix client run lint